spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_BASE:postgres}?prepareThreshold=0
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: ${DB_PG_POOL_SIZE:20}
  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
    enabled: true
jwt:
  secret: ${JWT-SECRET:bababoooyey}
  expiration: ${JWT-EXPIRATION:120000}